### ISSUE TITLE
Problem defining units

### ISSUE THREAD

**Issue by ewanorr** [josdejong/mathjs#1164]
We are trying to define units that denote "places" in a number. For example,  1.123 ones in tenths is 11.23 tenths. We defined the following units. 

```
    math.createUnit("tenths", {
        aliases: ["tenth", "tenths"],
    });

    math.createUnit("one", {
        definition: "10 tenths",
        aliases: ["one", "ones"],
    });

    math.createUnit("tens", {
        definition: "10 one",
        aliases: ["ten", "tens"],
    });
```

However, we came across an error when we tried to alias our "one" unit with "ones". Everything worked fine with "one", for example

```mathjs.eval("1 tenth in one")```
```
Unit {
  units: [ { unit: [Object], prefix: [Object], power: 1 } ],
  dimensions: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ],
  value: 1,
  fixPrefix: true,
  isUnitListSimplified: true }
```

But with "ones" (plural) it failed

```mathjs.eval("1 tenth in ones")```
```
TypeError: Unexpected type of argument in function to (expected: Unit or string or Array or Matrix or number or boolean, actual: function, index: 1)
    at createError (/Users/henryjaipuna/AmI/node_modules/typed-function/typed-function.js:555:19)
    at generic (/Users/henryjaipuna/AmI/node_modules/typed-function/typed-function.js:1077:15)
    at to (/Users/henryjaipuna/AmI/node_modules/typed-function/typed-function.js:1092:24)
    at evalOperatorNode (/Users/henryjaipuna/AmI/archetypeBuilder/node_modules/mathjs/lib/expression/node/OperatorNode.js:90:16)
    at Object.evalNode [as eval] (/Users/henryjaipuna/AmI/archetypeBuilder/node_modules/mathjs/lib/expression/node/Node.js:48:16)
    at string (/Users/henryjaipuna/AmI/archetypeBuilder/node_modules/mathjs/lib/expression/function/eval.js:43:36)
    at Object.compile (/Users/henryjaipuna/AmI/node_modules/typed-function/typed-function.js:1085:85)
```

Perhaps "ones" is a reserved mathJs? I couldn't see it mentioned in the docs. Sorry if this has already been addressed or if we are using units incorrectly.

**Comment by ericman314** [comment]
That's exactly right. `ones` is a built-in function. Currently, creating a unit will not override a built-in function. As a quick workaround, if it will work for your use case, you could preprocess the input to change "ones" to "one" or even "_ones" or something similar. There's probably a more elegant solution, but that's just a quick idea.

**Comment by ewanorr** [comment]
Thank you Eric; we might adopt the solution you suggested. Again, that helps a lot.
