### ISSUE TITLE
Error when importing most recently published version (v5.10.1)

### ISSUE THREAD

**Issue by cmccall** [josdejong/mathjs#1515]
We have a dependency on mathjs. No code around it has changed in quite some time, but today I started seeing the following error trace:
```
Error: Factory object with properties `type`, `name`, and `factory` expected
    at load (/opt/rdk/node_modules/mathjs/lib/core/core.js:94:13)
    at Object.factory (/opt/rdk/node_modules/mathjs/lib/type/matrix/utils/getArrayDataType.js:4:17)
    at load (/opt/rdk/node_modules/mathjs/lib/core/core.js:106:28)
    at Object.factory (/opt/rdk/node_modules/mathjs/lib/type/matrix/DenseMatrix.js:18:26)
    at load (/opt/rdk/node_modules/mathjs/lib/core/core.js:106:28)
    at resolver (/opt/rdk/node_modules/mathjs/lib/core/function/import.js:220:24)
    at _importFactory (/opt/rdk/node_modules/mathjs/lib/core/function/import.js:256:27)
    at mathImport (/opt/rdk/node_modules/mathjs/lib/core/function/import.js:74:7)
    at /opt/rdk/node_modules/mathjs/lib/core/function/import.js:77:9
    at Array.forEach (<anonymous>)
```

This occurs at module load time (the code that uses mathjs is not yet called) -- I suspect this is an issue with the latest published version? The semver range in our package.json allowed for this latest publish to be grabbed. Changing our semver import to be explicit on the last version we had tested with (5.3.0 -- this is old code) resolved this issue, so I suspect theres an issue with the newly published package. This is a node 8 LTS environment.

**Comment by josdejong** [comment]
Thanks for reporting. Did this issue start when jumping from `v5.10.0` to `v5.10.1`? Or somewhere between `v5.3.0` and the latest version?

**Comment by cmccall** [comment]
Somewhere between 5.3.0 and 5.10.1 -- looking at my package-lock, I can verify it was fine at 
`5.4.0`as well as thats the last locked version we had. I've done a full rebuild after the verification that 5.3.0 was working and gone back to 5.10.1 to re-verify and it seems to be working fine now, so I can no longer reproduce. 

I'm guessing it was some snafu in transferring the tarball between npm and our proxy server or such, since it happened right when the release went live.

**Comment by harrysarson** [comment]
We have had another report of this #1516. Lets investigate this there
