### ISSUE TITLE
Error occurs when requiring mathjs 5.10.1 in node.js

### ISSUE THREAD

**Issue by neuronaut** [josdejong/mathjs#1517]
As I get a different error I'm not sure whether this is the same as issue #1516, but when I require mathjs 5.10.1 in node.js (I'm using 12.1 if that makes a difference) I get the following error: "Factory object with properties \`type\`, \`name\`, and \`factory\` expected"

My steps to repro are:

`$ mkdir mathjs-test; cd mathjs-test`
`$ yarn init` (use all defaults here)
`$ yarn add mathjs`
`$ node`
`> require('mathjs');`

Resuls:

Thrown:
Error: Factory object with properties `type`, `name`, and `factory` expected
    at load (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/core.js:94:13)
    at Object.factory (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/type/matrix/utils/getArrayDataType.js:4:17)
    at load (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/core.js:106:28)
    at Object.factory (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/type/matrix/DenseMatrix.js:18:26)
    at load (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/core.js:106:28)
    at resolver (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/function/import.js:220:24)
    at _importFactory (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/function/import.js:256:27)
    at mathImport (/Users/thomasjones/Development/node/mathjs-test/node_modules/mathjs/lib/core/function/import.js:74:7)

**Comment by harrysarson** [comment]
What version of mathjs did you upgrade from?

**Comment by neuronaut** [comment]
In my test project I didn't upgrade -- just did a direct install of the latest (5.10.1). In my real project I was using 5.8.0 and later 5.9.0 both without issue, but got the above error after upgrading.

**Comment by harrysarson** [comment]
What OS are you on?

**Comment by harrysarson** [comment]
Lets investigate over at #1516
