### ISSUE TITLE
`eigs` throws TypeError for some BigNumber matrices

### ISSUE THREAD

**Issue by professorchaos97** [josdejong/mathjs#1789]
The `eigs` function throws a `TypeError` for some (but not all) matrices using `BigNumber`.

This example from `eigs.test.js` works as expected:
```javascript
var A = [
    [-4.78, -1.0, -2.59, -3.26, 4.24, 4.14],
    [-1.0, -2.45, -0.92, -2.33, -4.68, 4.27],
    [-2.59, -0.92, -2.45, 4.17, -3.33, 3.05],
    [-3.26, -2.33, 4.17, 2.51, 1.67, 2.24],
    [4.24, -4.68, -3.33, 1.67, 2.80, 2.73],
    [4.14, 4.27, 3.05, 2.24, 2.73, -4.47]
];
A = math.bignumber(A);
const ans = math.eigs(A);
```

However, the following example produces a `TypeError`:
```javascript
var B = [
    [0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
    [1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 1.0, 0.0, 0.0],
    [0.0, 0.0, 1.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
    [1.0, 0.0, 0.0, 0.0, 1.0, 0.0]
];
B = math.bignumber(B);
const ans2 = math.eigs(B);
```
```javascript
TypeError: Cannot implicitly convert a number with >15 significant digits to BigNumber (value: 0.7071067811865476). Use function bignumber(x) to convert to BigNumber.
    at convert (/home/professorchaos/Dokumente/javascript/node_modules/mathjs/lib/core/function/typed.js:208:15)
    at Array.convertArg (/home/professorchaos/Dokumente/javascript/node_modules/typed-function/typed-function.js:819:22)
    at convertArgs (/home/professorchaos/Dokumente/javascript/node_modules/typed-function/typed-function.js:766:45)
    at generic (/home/professorchaos/Dokumente/javascript/node_modules/typed-function/typed-function.js:1073:27)
    at multiplyScalar (/home/professorchaos/Dokumente/javascript/node_modules/typed-function/typed-function.js:1092:24)
    at Sij1Big (/home/professorchaos/Dokumente/javascript/node_modules/mathjs/lib/function/matrix/eigs.js:274:25)
    at diagBig (/home/professorchaos/Dokumente/javascript/node_modules/mathjs/lib/function/matrix/eigs.js:202:13)
    at checkAndSubmit (/home/professorchaos/Dokumente/javascript/node_modules/mathjs/lib/function/matrix/eigs.js:143:14)
    at Array (/home/professorchaos/Dokumente/javascript/node_modules/mathjs/lib/function/matrix/eigs.js:73:17)
    at Object.eigs (/home/professorchaos/Dokumente/javascript/node_modules/typed-function/typed-function.js:1085:85)
```
I'm using math.js v6.6.1, the problem occurs both in node and in the browser using `math.min.js`. Let me know if you need any additional info.

**Comment by josdejong** [comment]
Thanks for reporting. It turned out the BigNumber implementation of `eigs` was calculated using a mix of numbers and BigNumbers, causing the output to have number precision only in some cases like your example. 

Fix created, not yet published.

**Comment by josdejong** [comment]
Fixed now in `v6.6.2`

**Comment by professorchaos97** [comment]
Thanks very much for the quick fix! On an unrelated note, seeing as you already have a `precision` parameter in the `diag` and `diagBig` functions in `eigs.js`, would it be possible to pass the precision from `eigs`? Should I open a new issue for this?

**Comment by josdejong** [comment]
That's a very good point @professorchaos97 . I've addressed this in this commit: https://github.com/josdejong/mathjs/commit/7e8d128bd61f613e6b90eee489e31f8dbbda4066, so the function `eigs` consistently uses `config.epsilon` (not yet published). 

Does that address your concern?

**Comment by professorchaos97** [comment]
Yes, it does. Thanks again!

**Comment by josdejong** [comment]
👍
