### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined when run in jest

### ISSUE THREAD

**Issue by junbujianwpl** [josdejong/mathjs#1898]
`yarn jest --testPathPattern path/to/file
yarn run v1.22.4
$ D:\workspace\js\myproject\node_modules\.bin\jest --testPathPattern path/to/file
 FAIL  path/to/xxx.spec.ts
  ● Test suite failed to run

      ● Test suite failed to run

        TypeError: Cannot read property 'prototype' of undefined

      at Object.<anonymous>.createComplexClass.isClass (node_modules/mathjs/lib/type/complex/Complex.js:28:23)
      at assertAndCreate (node_modules/mathjs/lib/utils/factory.js:49:12)
      at Object.<anonymous> (node_modules/mathjs/lib/entry/pureFunctionsAny.generated.js:24:38)
      at Object.<anonymous> (node_modules/mathjs/lib/entry/mainAny.js:53:25)`

It can be produced with the latest at least three versions. It works fine in my project when run the project by running `npm run start`.  So why this is not working with jest.

**Comment by josdejong** [comment]
Thanks for reporting. How can I reproduce this issue?

**Comment by Git-on-my-level** [comment]
I was able to reproduce this, it involves using babel-jest
I created a minimal reproducible repo here:
https://github.com/Git-on-my-level/mathjs-jest-issue-1898

**Comment by Git-on-my-level** [comment]
My fix was rather than including `.` as a target in `moduleDirectories` I had to explicitly list all my directories.

# Example
Instead of
```
module.exports = {
  moduleDirectories: ["node_modules", "."],
};
```

Replace with
```
module.exports = {
  moduleDirectories: ["node_modules", "explicit", "directories", "instead"],
};
```

I'm not familiar enough with jest to root cause this, but hope this helps

**Comment by josdejong** [comment]
Thanks a lot for working out this example David! 

We're working on improved support for ES modules and Commonjs in the library (see #1941, #1962), it will be interesting to see if we can solve this issue with Jest (or maybe it's even already fixed in this PR).

**Comment by josdejong** [comment]
mathjs v8 was released a few days ago. This improved ES modules support which also gave trouble with Jest.

Can anyone see if this issue still occurring in v8?

**Comment by Git-on-my-level** [comment]
Using my above repo but updating `mathjs` to `8.0.1` still results in the same error

**Comment by josdejong** [comment]
Thanks for checking 👍 

We'll keep this issue open and have to do more digging then. Anyone able to help?
