### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by bettem** [josdejong/mathjs#1989]
I am importing this library into a React component defined in TypeScript using the import:
`import * as math from 'mathjs';`

Without using any part/function/type of the library, all my tests now fail with a TypeError. The error given is:
```

  ● Test suite failed to run

    TypeError: Cannot convert a Symbol value to a string
        at Array.join (<anonymous>)
        at Array.toString (<anonymous>)
        at Array.join (<anonymous>)
        at Array.toString (<anonymous>)
        at Array.join (<anonymous>)
        at Array.toString (<anonymous>)

      1 | import jp from 'jsonpath';
      2 | import isArray from 'lodash/isArray';
    > 3 | import * as math from 'mathjs';
        | ^
      4 | import React  from 'react';
      5 | 

      at mixkey (node_modules/seed-random/index.js:135:25)
      at Object.<anonymous>.module.exports (node_modules/seed-random/index.js:35:19)
      at Object.<anonymous> (node_modules/mathjs/lib/function/probability/util/seededRNG.js:18:65)
      at Object.<anonymous> (node_modules/mathjs/lib/function/probability/pickRandom.js:14:18)
      at Object.<anonymous> (node_modules/mathjs/lib/factoriesAny.js:2427:19)
      at Object.<anonymous> (node_modules/mathjs/lib/entry/pureFunctionsAny.generated.js:12:21)
      at Object.<anonymous> (node_modules/mathjs/lib/entry/mainAny.js:53:25)
      at Object.<anonymous> (node_modules/mathjs/main/es5/index.js:1:107)
      at Object.<anonymous> (src/components/form/formField/formField.tsx:3:1)
      at Object.<anonymous> (src/components/form/formField/index.js:1:1)
      at Object.<anonymous> (src/components/form/inputs/creditor/creditor.js:19:1)
      at Object.<anonymous> (src/app/form/validator.js:14:1)
      at Object.<anonymous> (src/app/form/index.js:1:1)
      at Object.<anonymous> (src/components/form/inputs/string/string.js:7:1)
      at Object.<anonymous> (src/components/form/inputs/index.js:17:1)
      at Object.<anonymous> (src/components/form/inputs/anzsco/anzsco.test.js:16:1)


```
The tests are written in Jest and do not use the library at all. This error did not occur when the component was written in regular JavaScript. 

Is there something I need to do to avoid this TypeError?

**Comment by josdejong** [comment]
This may be related to an issue with the `seed-random` library, see #1949, #1955. The fix (replacing the library) is scheduled for `v8` but not yet published.

**Comment by josdejong** [comment]
mathjs `v8` has been published a while ago. @bettem can you try out if the issue you reported is solved?

**Comment by josdejong** [comment]
I'll assume the issue is fixed. Please reopen if there is still an issue.
