### ISSUE TITLE
eigs finds wrong eigenvectors

### ISSUE THREAD

**Issue by m93a** [josdejong/mathjs#2345]
Searching for eigenvalues and eigenvectors of the matrix `1, 2; 3, 4` produces:
```javascript
math.eigs([
  [1, 2],
  [3, 4]
])
→ {
    values: [-0.3723, 5.372],
    vectors: [
        [1e-17, 2.331],
        [-1.000, 5.097]
    ]
}
```
while the eigenvalues are correct, the eigenvectors are nonsense. The correct eigenvectors are:
```javascript
[
   [0.4574, 1],
   [-1.457, 1]
]
```

**Comment by josdejong** [comment]
🤔 . Are the vectors always nonsense or just in this specific case?

**Comment by m93a** [comment]
I've definitely tested a few matrices after implementing `eigs` for complex matrices and the results were correct for them. But since I don't know what causes this bug yet, I'm not sure how widespread it is... 🤔

**Comment by josdejong** [comment]
Maybe there is somewhere a numerical instability causing these issues, I see `1e-17` in the vectors.

**Comment by davidtranhq** [comment]
I'm looking into this! I brought this bug to m93a's attention and we suspect it may have something to do with the way the Francis algorithm keeps track of transformations.

**Comment by apourzand** [comment]
Another case is when calculating the eigenvalues of 
```
math.eigs([
  [1, 0],
  [1, 1]
])
```
Here is my code:

```
const math = require('mathjs');
let x = math.matrix([[1, 0], [1, 1]]); 
console.log(math.eigs(x));
```

It throws an error like this:

```
C:\projects\numberTheory\node_modules\mathjs\lib\cjs\function\matrix\eigs\complexEigs.js:500
      throw err;
      ^

Error: Failed to find eigenvectors for the following eigenvalues: 0.9999999999999998
    at findEigenvectors (C:\projects\numberTheory\node_modules\mathjs\lib\cjs\function\matrix\eigs\complexEigs.js:497:17)
    at complexEigs (C:\projects\numberTheory\node_modules\mathjs\lib\cjs\function\matrix\eigs\complexEigs.js:82:17)
    at computeValuesAndVectors (C:\projects\numberTheory\node_modules\mathjs\lib\cjs\function\matrix\eigs.js:183:12)
    at Function.Matrix (C:\projects\numberTheory\node_modules\mathjs\lib\cjs\function\matrix\eigs.js:137:35)
    at Object.eigs (C:\projects\numberTheory\node_modules\typed-function\typed-function.js:1088:85)
    at Object.<anonymous> (C:\projects\numberTheory\euclid.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  values: [ 0.9999999999999998, 0.9999999999999998 ],
  vectors: []
}

```

While the eigenvalue is double 1.

**Comment by m93a** [comment]
@apourzand The behavior you report is correct. The algorithm finds the two eigenvalues, but fails to find eigenvectors – this is fine, as the matrix is a Jordan cell, therefoere **not** diagonalizable. Sadly, there isn't a way to only run the eigen**value** search without also searching for eigen**vectors** – for that, see #2180.

**Comment by davidtranhq** [comment]
Looks like this was fixed with https://github.com/josdejong/mathjs/issues/2478 !

**Comment by josdejong** [comment]
O that is a nice surprise 😄 

I just checked and you're right. I'll close this issue.
