### ISSUE TITLE
Support for non-integer exponents in 'BigNumber' types

### ISSUE THREAD

**Issue by Uranialuminum** [josdejong/mathjs#2586]
Hi guys. So I'm currently using math.js to write a chemical computation program, and whenever I use non-integer exponents (which is a pretty common thing in chemistry) to create a new BigNumber, for example:
```
// file test2.js
import {create, all} from 'mathjs'
const config = {}
const math = create(all, config);
console.log(math.bignumber('1e9.2'));
```
I get the following error message:
```
D:\code\node_modules\decimal.js\decimal.js:3620
      throw Error(invalidArgument + str);
            ^

Error: [DecimalError] Invalid argument: 1e9.2
    at parseOther (D:\code\node_modules\decimal.js\decimal.js:3620:13)
    at new Decimal (D:\code\node_modules\decimal.js\decimal.js:4386:55)
    at Function.string (file:///D:/code/node_modules/mathjs/lib/esm/type/bignumber/function/bignumber.js:66:14)
    at Object.bignumber (D:\code\node_modules\typed-function\typed-function.js:1089:85)
    at file:///D:/code/test2.js:4:18
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```
I understand this as math.js doesn't have support for non-integer exponents yet, as I haven't seen any code in the issues or in the docs that use non-integer exponents. If this feature is added it's going to be great help for me and possibly a lot of other people wanting to write a scientific computation program, so can we please have it?

I'm pretty new to coding and English isn't my first language, so please forgive me if I made any mistakes above.

**Comment by Uranialuminum** [comment]
Update: I found a workaround by basically breaking the non-integer exponent into the integer part and the decimal part, then using roots and exponents, but I think there's going too be some performance compromise (although I don't really know what to compare to).

**Comment by josdejong** [comment]
Ah, interesting. I've never used non-integer exponents myself, but it makes sense to support it. 

We have to think through the implications before we implement this, this number notation is not supported by JavaScript itself and neither by the libraries like Decimal.js (used as `BigNumber`), so we would need to carefully refactor all points where a string can be parsed into a numeric type.

From the top of my mind, this involves the following functions/classes:

```js
math.number('1e9.2')
math.bignumber('1e9.2')
new math.BigNumber('1e9.2') // not part of mathjs itself
math.evaluate('1e9.2')
math.unit('1e9.2', 'm')
``` 

As a workaround, you can indeed write `math.evaluate('1e9.2')` as `math.evaluate('1*10^9.2')` for example.

**Comment by Uranialuminum** [comment]
Thanks for the reply!
Your solution of writing `math.evaluate('1*10^9.2')` works even better than my solution of:

```import {create, all} from 'mathjs'
const config = {}
const math = create(all, config);

function nonIntExp(num) {
    if (isNaN(Number(num)) || Number(num) === Number.POSITIVE_INFINITY || Number(num) === Number.NEGATIVE_INFINITY) {
        return 'Not a viable number!';
    }
    if (num.includes('.')) {
        const split = num.split('.');
        return math.bignumber(math.divide(math.bignumber('1e' + split[0]), math.nthRoot(math.bignumber('1e' + split[1]), math.bignumber('1e' + split[1].length))));
    } else {
        return math.bignumber('1e' + num);
    }
}
```

Because `math.evaluate('1*10^9.2')` gives a pretty comfortable number of significant figures when used as-is (at least for my purpose), while `nonIntExp()` above gives a pretty massive number of sig figs without any specifications in `config` since it basically returns a BigNumber.

Thank you!

Also, just a little thing I came across, `math.evaluate('1*10^9.2')` returns a `number` type instead of an `object` like the BigNumber above. I didn't know JS supported that big/small of numbers OR supported scientific notation! Because `math.evaluate('1*10^-9.2')` gave `6.309573444801942e-10`, which I was pretty surprised to see was a number type.

**Comment by josdejong** [comment]
What `math.evaluate('1*10^9.2')` returns depends on the configuration. To have it return a BigNumber instead:

```js
math.config({ number: 'BigNumber' })

const result = math.evaluate('1*10^9.2') // BigNumber
console.log(result.toString()) // "1584893192.461113485202101373391507013269442133825039068316296812"
```

You can create a little helper function around this and import that in mathjs (or overwrite the default `math.bignumber()` function with your extended version).

I see you've close this issue because you have a satisfying workaround. This is fine with me, but if this is an issue for many people please let's open it and think through how to implement support for it in mathjs itself.
