### ISSUE TITLE
Import error with Vite SSR (Nuxt 3, dev only)

### ISSUE THREAD

**Issue by matteomejia** [josdejong/mathjs#2837]
**Describe the bug**
Using v11.3.2 in a Nuxt 3 project in development mode, import fails with the following error:

```
[nuxt] [request error] [unhandled] [500] __vite_ssr_import_0__.default is not a function
  at ./node_modules/mathjs/lib/esm/entry/configReadonly.js:16:30
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async ./node_modules/mathjs/lib/esm/entry/mainAny.js:2:31
  at async ViteNodeRunner.directRequest (./node_modules/vite-node/dist/client.mjs:250:5)
  at async ViteNodeRunner.cachedRequest (./node_modules/vite-node/dist/client.mjs:129:12)
  at async request (./node_modules/vite-node/dist/client.mjs:152:16)
  at async mathjs:1:238
```

**To Reproduce**
In any Nuxt 3 page, import and call mathjs

```html
<script lang="ts" setup>
import {create, all} from 'mathjs';
const mathjs = create(all);
</script>
```
Repo with working reproduction: [repo](https://github.com/matteomejia/mathjs-nuxt)

**Comment by josdejong** [comment]
Thanks for reporting. I cloned your repo and started it with `npm install; npm run dev`, and things work just fine, I don't get the error you report. Can this be related to using a brand new release candidate `nuxt@3.0.0-rc.13`?

**Comment by matteomejia** [comment]
It does seem to be related to Nuxt 3. I did a test with a simple Vite SSR app and it worked, but using any of the latest Nuxt 3 RCs gives me the same error. Might have to open an issue there.

**Comment by josdejong** [comment]
So, shall we close this issue for now, assuming that it is a Nuxt 3 related issue? If it turns out otherwise we can have another look.

**Comment by matteomejia** [comment]
Yes, issue will be tracked in the Nuxt 3 repo. Closing now.
