### ISSUE TITLE
Source Maps, Ember, and Mathjs (Not Sitting in a Tree)

### ISSUE THREAD

**Issue by jherdman** [josdejong/mathjs#300]
I've found the following error when building an Ember project:

```
Build failed.
ENOENT, no such file or directory '/Users/james/xyz/tmp/tree_merger-tmp_dest_dir-WZt9LsZb.tmp/bower_components/mathjs/dist/dist/math.js'
Error: ENOENT, no such file or directory '/Users/james/xyz/tmp/tree_merger-tmp_dest_dir-WZt9LsZb.tmp/bower_components/mathjs/dist/dist/math.js'
  at Error (native)
  at Object.fs.openSync (fs.js:502:18)
  at Object.fs.readFileSync (fs.js:354:15)
  at SourceMap.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:270:17)
  at Array.map (native)
  at SourceMap._resolveSourcesContent (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:263:27)
  at SourceMap._assimilateExistingMap (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:242:63)
  at SourceMap.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:216:10)
  at SourceMap._cacheEncoderResults (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:124:16)
  at SourceMap._addMap (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:215:8)
  at SourceMap.addFileSource (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:91:19)
  at SourceMap.addFile (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/fast-sourcemap-concat/lib/source-map.js:69:15)
  at Class.<anonymous> (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:85:21)
  at Array.forEach (native)
  at Class.module.exports.CachingWriter.extend.addFiles (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:78:8)
  at Class.module.exports.CachingWriter.extend.updateCache (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
  at /Users/james/PN/es-student/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
  at lib$rsvp$$internal$$tryCatch (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/Users/james/PN/es-student/node_modules/ember-cli/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:1290:9)
  at process._tickCallback (node.js:355:11)
```

It seems to me that the problem is that the location for the sourcemap doesn't make much sense insofar that it's assuming the directory structure I'm using. Shouldn't it look sort of like the below?

```
{"version":3,"file":"math.map","sources":["math.js"] <snip>
```

**Comment by josdejong** [comment]
Sorry, what should look like that? Can you explain the context?

**Comment by jherdman** [comment]
My apologies. The source map should look like my sample. It currently looks like this:

```
{"version":3,"file":"math.map","sources":["./dist/math.js"] <snip>
```
The problem is that the sources path is wrong. The dist directory in which the source map, development, and production mathjs files live do not contain a "dist" directory.

To illustrate, the above implies the following structure:

```
bower_components/mathjs/dist                                                                                       │
|--- math.js                                                                                                        │
|--- math.map                                                                                                       │
|--- math.min.js
|--- dist
|------ math.js
```

When in reality we have this structure:

```
bower_components/mathjs/dist                                                                                       │
|--- math.js                                                                                                        │
|--- math.map                                                                                                       │
|--- math.min.js
```

**Comment by josdejong** [comment]
And where is this `{"version":3,"file":"math.map","sources":["./dist/math.js"] <snip>` coming from?

**Comment by jherdman** [comment]
[Here](https://github.com/josdejong/mathjs/blob/4a8c3cb4f18ac27704c74f8e3e3b49890a674fca/dist/math.map).

**Comment by josdejong** [comment]
Ah ok, got it. Thanks. This map file is generated by uglifyjs, I think the base path is configurable.

**Comment by josdejong** [comment]
This issue has been solved now in the `develop` branch thanks to a fix of @jherdman
