### ISSUE TITLE
browserify Error: Cannot find module ‘typed-function’ from…

### ISSUE THREAD

**Issue by masterj63** [josdejong/mathjs#499]
I just have cloned the sources of `mathjs` and tried to create custom bundle.

```
$ cd mathjs/examples/advanced
$ browserify custom_loading.js -o my_bundle.js
Error: Cannot find module ‘typed-function' from '/Users/username/mathjs/lib/core'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Is it a bug?

**Comment by josdejong** [comment]
Did you run `npm install` after cloning the library to install the dependencies like `typed-function`?

**Comment by josdejong** [comment]
Is this still an issue?

**Comment by masterj63** [comment]
It’s not already, I made it work, thanks!

**Comment by josdejong** [comment]
Ok thanks for the update.
