### ISSUE TITLE
TypeError: Cannot read property 'dimensions' of undefined

### ISSUE THREAD

**Issue by samundrak** [josdejong/mathjs#535]
i just install this module and required in my file got this error?
#  TypeError: Cannot read property 'dimensions' of undefined
    at Object.factory (/home/samundrak/vdiscover/node_modules/mathjs/lib/type/unit/Unit.js:2580:32)
    at load (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/core.js:104:28)
    at Object.factory (/home/samundrak/vdiscover/node_modules/mathjs/lib/type/complex/Complex.js:8:14)
    at load (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/core.js:104:28)
    at resolver (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/import.js:188:24)
    at Object.defineProperty.get [as Complex] (/home/samundrak/vdiscover/node_modules/mathjs/lib/utils/object.js:182:20)
    at Object.factory (/home/samundrak/vdiscover/node_modules/mathjs/lib/constants.js:60:20)
    at load (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/core.js:101:28)
    at _importFactory (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/import.js:223:7)
    at math_import (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/import.js:68:7)
    at /home/samundrak/vdiscover/node_modules/mathjs/lib/core/import.js:73:9
    at Array.forEach (native)
    at Object.math_import [as import] (/home/samundrak/vdiscover/node_modules/mathjs/lib/core/import.js:72:14)
    at create (/home/samundrak/vdiscover/node_modules/mathjs/index.js:32:17)
    at Object.<anonymous> (/home/samundrak/vdiscover/node_modules/mathjs/index.js:38:18)
    at Module._compile (module.js:434:26)

**Comment by josdejong** [comment]
Thanks for your report. What version of node.js and what operating system are you using?

**Comment by josdejong** [comment]
Also, can you post the code you use to load math.js?

**Comment by samundrak** [comment]
i am using node v4 on ubuntu 14lts . i just require the module and got error

**Comment by josdejong** [comment]
ok thanks, and what version of math.js are you using?

**Comment by samundrak** [comment]
i didnt saw the version ,i just installed this module first time today just by npm i mathjs --save

**Comment by josdejong** [comment]
OK so that should be the latest version then. I will try to reproduce this, I haven't seen this before.

**Comment by josdejong** [comment]
hm, I've installed Ubuntu 14.04 lts in Virtualbox, installed node.js 4.2.4, then `npm i mathjs`, then load node and run `var math = require('mathjs')`, that works just fine. So it's probably not a generic problem for this OS and node.js version.

Maybe you could try to throw away your `node_modules` folder and reinstall mathjs, see if the problem still exists?

**Comment by samundrak** [comment]
Ok its working after re-installation thanks !!!

**Comment by josdejong** [comment]
ok great!
