### ISSUE TITLE
Question: Physical constants with eval?

### ISSUE THREAD

**Issue by arve0** [josdejong/mathjs#861]
Should one be able to use [physical constants](http://mathjs.org/docs/datatypes/units.html#physical-constants) with `eval`?

I'm doing this and it throws:
```js
$ node bin/repl.js 
> math.eval("speedOfLight")
Error: Undefined symbol speedOfLight
    at undef (/Users/arve/git/mathjs/lib/expression/node/SymbolNode.js:111:11)
    at Object.eval (eval at <anonymous> (/Users/arve/git/mathjs/lib/expression/node/Node.js:73:19), <anonymous>:3:443)
    at string (/Users/arve/git/mathjs/lib/expression/function/eval.js:43:36)
    at Object.compile (eval at _typed (/Users/arve/git/mathjs/node_modules/typed-function/typed-function.js:1115:22), <anonymous>:22:14)
    at repl:1:6
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:513:10)
```

I've also tried:
```js
> math.eval("c = speedOfLight")  // Error: Undefined symbol speedOfLight
> math.eval("c")  // Error: Undefined symbol c
```

**Comment by josdejong** [comment]
Thanks for reporting, this is a bug, `math.eval('speedOfLight')` should just work. This issue has been introduced when securing the expression parser. Shouldn't be too hard to solve.

**Comment by josdejong** [comment]
The issue has been fixed now in `develop`, awaiting the first next release.
