### ISSUE TITLE
Cannot find module './docs' from 'index.js'

### ISSUE THREAD

**Issue by josephfinlayson** [josdejong/mathjs#906]
```
  ● Test suite failed to run

    Cannot find module './docs' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/mathjs/lib/expression/index.js:2:3)
```

`expression/index.js` requires `./docs` and this cannot be found in the folder

```
module.exports = [
  require('./docs'),
  require('./function'),
  require('./node'),
  require('./transform'),

  require('./Help'),
  require('./parse'),
  require('./Parser')
];
```

I have solved this by commenting it out. Using `typescript` and `node v6.6.0`

**Comment by josdejong** [comment]
> I have solved this by commenting it out. 

hm, that doesn't really sound like a solution...

Similar issue: #809
