### ISSUE TITLE
Build Failure due to Webpack 2

### ISSUE THREAD

**Issue by rwieruch** [josdejong/mathjs#985]
I am running MacOs with

```
node -v
v8.3.0

npm -v
5.6.0
```

I wanted to build the library on my local machine. After going through

```
git clone git://github.com/josdejong/mathjs.git
cd mathjs
npm install
npm run build
```

I hit the following error for my build:

```
/Users/foobar/Developer/Repos/mathjs/gulpfile.js:59
    new webpack.optimize.ModuleConcatenationPlugin()
    ^

TypeError: webpack.optimize.ModuleConcatenationPlugin is not a constructor
    at Object.<anonymous> (/Users/foobar/Developer/Repos/mathjs/gulpfile.js:59:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

In order to fix it, I had to upgrade Webpack 2 to Webpack 3:

```
-    "webpack": "2.6.1",
+    "webpack": "3.10.0",
```

Not sure, if anyone else ran into this issue or if it is only on my side. I can open a PR for it and you decide whether it's an improvement or not. Not sure if there needs be anything else updated when upgrading Webpack though.

**Comment by josdejong** [comment]
Should be fixed now in v3.18.0
